baseURL = "https://diazepam.cc/"
languageCode = "zh-cn"
title = "Diazepam's Zone"
theme = "github-style"
googleAnalytics = "G-DDLTSB3FYD"
copyright = "Theme by <a href='https://github.com/MeiK2333/github-style'>github-style</a>"
pygmentsCodeFences = true
pygmentsUseClasses = true
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  author = "Diazepam"
  description = "Enjoy everyday!"
  github = "Metaphorme"
  email = "77@diazepam.cc"
  url = "https://diazepam.cc"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "🌏"
  favicon = "/images/dna.png"
  location = "Nanjing, Jiangsu, China"
  enableGitalk = true
  enableSearch = true

  [params.gitalk]
    clientID = "e634d9a28d7aa0a810f5" 
    clientSecret = "7493396cb521167eaa0893b3058a1aba6baddcef" 
    repo = "metaphorme.github.io"
    owner = "Metaphorme"
    admin = "Metaphorme"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://diazepam.cc"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

